#!/usr/bin/env pyenv exec python3

# File: picli

import argparse
from utils.ip import get_local_ip, get_router_ip, scan_hosts


def main():
    parser = argparse.ArgumentParser(description="Network Scanner")
    parser.add_argument(
        "--scan",
        action="store_true",
        help="Scan for active hosts on the local network",
    )
    args = parser.parse_args()

    ip = get_local_ip()
    print("Local IP Address:", ip)

    router = get_router_ip()
    print("Router IP Address:", router)

    if args.scan:
        hosts = scan_hosts()
        print("Active Hosts:")
        for host in hosts:
            print(host)


if __name__ == "__main__":
    main()
