#!/usr/bin/env pyenv exec python3

# File: picli

import argparse
import subprocess
from utils.ip import scan_ips
import game_of_life


def main():
    parser = argparse.ArgumentParser(description="Python CLI Tools")
    # parser.add_argument(
    #     "--scan",
    #     action="store_true",
    #     help="Scan for active hosts on the local network",
    # )
    subparser = parser.add_subparsers(dest="command")

    subparser.add_parser(
        "scan-ip", help="Scan for active hosts on the local network"
    )

    gol = subparser.add_parser(
        "game-of-life", help="Run Conway's Game of Life"
    )
    gol.add_argument(
        "--width",
        type=int,
        default=10,
        help="Width of the game board",
    )
    gol.add_argument(
        "--height",
        type=int,
        default=10,
        help="Height of the game board",
    )

    args = parser.parse_args()

    try:
        if args.command == "scan-ip":
            scan_ips()
        if args.command == "game-of-life":
            game_of_life.start(args.width, args.height)
    except KeyboardInterrupt:
        print("\nOperation cancelled by user.")


if __name__ == "__main__":
    main()
