#!/usr/bin/env pyenv exec python3

# File: picli

import argparse
from utils.ip import scan_ips
from GameOfLife import GameOfLife


def main():
    parser = argparse.ArgumentParser(description="Python CLI Tools")
    subparser = parser.add_subparsers(dest="command")

    subparser.add_parser(
        "scan-ip", help="Scan for active hosts on the local network"
    )

    gol = subparser.add_parser(
        "game-of-life", help="Run Conway's Game of Life"
    )
    gol.add_argument(
        "--width",
        type=int,
        default=30,
        help="Width of the game board",
    )
    gol.add_argument(
        "--height",
        type=int,
        default=10,
        help="Height of the game board",
    )
    gol.add_argument(
        "--generations",
        type=int,
        default=300,
        help="Number of generations to simulate",
    )
    gol.add_argument(
        "--loop",
        action="store_true",
        help="Loop the simulation indefinitely",
        default=False,
    )

    args = parser.parse_args()

    try:
        if args.command == "scan-ip":
            scan_ips()
        if args.command == "game-of-life":
            gameOfLife = GameOfLife(args.width, args.height, args.generations)
            gameOfLife.start(args.loop)
    except KeyboardInterrupt:
        print("\nOperation cancelled by user.")


if __name__ == "__main__":
    main()
